#pragma once
#include "UIBox.h"
#include "../Vec3.h"
#include "../Vec2.h"

namespace kui
{
	class Shader;

	class UIBackgroundState
	{
	public:
		Vec3f Color;
		Vec3f BorderColor = 1;
		UISize BorderRadius = 0;
		UISize CornerRadius = 0;
		float Opacity = 1;
		uint8_t CornerFlags = 0b1111;
		uint8_t BorderFlags = 0b1111;
		bool OwnsTexture = false;
		bool UseTexture = false;
		unsigned int TextureID = 0;

		virtual ~UIBackgroundState() = default;

		virtual void Draw(render::RenderBackend* With, Vec2f Position, Vec2f Size, ScrollObject* Scroll) = 0;

	};

	/**
	 * @brief
	 * UI element that draws a square over the space it occupies.
	 *
	 * A UIBackground has many options for it's appearance,
	 * like adding a border, rounded corners, displaying an image, etc.
	 *
	 * Any element that displays border-type visuals (like buttons, text fields, etc.) should derive from this.
	 */
	class UIBackground : public UIBox
	{
	protected:
		void MakeGLBuffers();
		virtual void DrawBackground(render::RenderBackend* Backend);
		UIBackgroundState* State = nullptr;

	public:
		static float GetBorderSize(UISize InSize);

		/**
		 * @brief
		 * Checks if this background has an image applied to it.
		 * @return
		 * True if the background has an image applied to it, false if not.
		 *
		 * @see SetUseImage
		 */
		bool HasImage() const
		{
			return State->UseTexture;
		}

		Shader* BackgroundShader = nullptr;

		/**
		 * @brief
		 * Sets the opacity of the UIBackground.
		 *
		 * An opacity of 1 is fully visible, an opacity of 0 is completely transparent.
		 */
		UIBackground* SetOpacity(float NewOpacity);

		UIBackground* SetBorderColor(Vec3f NewColor);

		/**
		 * @brief
		 * Returns the opacity of the UIBackground.
		 */
		float GetOpacity() const;

		/**
		 * @brief
		 * Sets the color of the UIBackground.
		 */
		virtual UIBackground* SetColor(Vec3f NewColor);

		/**
		 * @brief
		 * Returns the color of the UIBackground.
		 */
		virtual Vec3f GetColor() const;

		/**
		 * @brief
		 * Same as SetUseImage, but with a different name for backwards compatibility.
		 */
		UIBackground* SetUseTexture(bool UseTexture, unsigned int TextureID = 0);
		UIBackground* SetUseTexture(bool UseTexture, std::string TextureFile);

		/**
		 * @brief
		 * Sets an image used by this UIBackground.
		 *
		 * The image will have the color of the UIBackground that was set with SetColor().
		 *
		 * @param UseTexture
		 * True if the background should use an image. False if not.
		 *
		 * @param TextureID
		 * The ID of any texture generated by kui::image::LoadImage() (or any OpenGL texture object).
		 *
		 * @return
		 * A pointer to this UIBackground, for chaining method calls.
		 */
		UIBackground* SetUseImage(bool UseImage, unsigned int TextureID = 0)
		{
			return SetUseTexture(UseImage, TextureID);
		}

		/**
		 * @brief
		 * Sets an image used by this UIBackground.
		 *
		 * The image will have the color of the UIBackground that was set with SetColor().
		 *
		 * @param UseTexture
		 * True if the background should use am image. False if not.
		 *
		 * @param TextureFile
		 * A resource path to the image to load if UseImage is true.
		 *
		 * @return
		 * A pointer to this UIBackground, for chaining method calls.
		 */
		UIBackground* SetUseImage(bool UseImage, std::string TextureFile)
		{
			return SetUseTexture(UseImage, TextureFile);
		}

		/**
		 * @brief
		 * Sets the border this background should have.
		 * @param BorderSize
		 * The size of the border.
		 * @param Color
		 * The color of the border
		 * @return
		 * A pointer to this UIBackground, for chaining method calls.
		 */
		UIBackground* SetBorder(UISize BorderSize, Vec3f Color);

		/**
		 * @brief
		 * Sets which edges of the background should have their border visible.
		 * @param Top
		 * Controls if the top border should be visible.
		 * @param Down
		 * Controls if the bottom border should be visible.
		 * @param Left
		 * Controls if the left border should be visible.
		 * @param Right
		 * Controls if the right border should be visible.
		 * @return
		 * A pointer to this UIBackground, for chaining method calls.
		 */
		UIBackground* SetBorderEdges(bool Top, bool Down, bool Left, bool Right);
		UIBackground* SetBorderVisible(int Index, bool Value);

		UIBackground* SetCorner(UISize CornerSize);
		UIBackground* SetCorners(bool TopLeft, bool TopRight, bool BottomLeft, bool BottomRight);
		UIBackground* SetCornerVisible(int Index, bool Value);

		UIBackgroundState* GetRenderState() const
		{
			return this->State;
		}

		/**
		 * @brief
		 * UIBackground constructor.
		 *
		 * @param Horizontal
		 * True if the children should be laid out horizontally, false if vertically.
		 *
		 * @param Position
		 * The position of the UIBackground. If it has a parent, this will be ignored.
		 *
		 * @param Color
		 * The color of the UIBackground.
		 *
		 * @param MinScale
		 * The MinScale value of the UIBackground.
		 *
		 * @param UsedShader
		 * The shader used by the UIBackground. If this is nullptr, the default shader is used.
		 */
		UIBackground(bool Horizontal, Vec2f Position, Vec3f Color, SizeVec MinScale = SizeVec::Smallest(), Shader* UsedShader = nullptr);
		virtual ~UIBackground();
		virtual void Draw(render::RenderBackend* Backend) override;
		void Update() override;
		void OnAttached() override;
	};
}