#include <Markup/WriteHeader.h>
#include <fstream>
#include <filesystem>
#include <sstream>
#include <iostream>

kui::markup::HeaderWriter::HeaderWriter(kui::markup::ParseResult* Parsed)
{
	this->Parsed = Parsed;
}

void kui::markup::HeaderWriter::Write(std::string Dir)
{
	std::filesystem::create_directories(Dir);

	for (auto& i : Parsed->Elements)
	{
		auto& File = ToWrite[i.FilePath];
		File.Name = i.File + ".hpp";
		File.Path = Dir + "/" + i.File + ".hpp";
		File.Elements.push_back({ &i, false, new ElementWriter(&i, Parsed)});
	}

	for (auto& [Path, Header] : ToWrite)
	{
		bool ShouldWrite = true;

		if (std::filesystem::exists(Header.Path))
		{
			if (std::filesystem::last_write_time(Path) < std::filesystem::last_write_time(Header.Path))
			{
				ShouldWrite = false;
			}
		}

		if (ShouldWrite)
		{
			std::ofstream Out = std::ofstream(Header.Path);

			Header.WriteElements(Out, this);
			Out.flush();
			Out.close();
		}
	}
}

void kui::markup::HeaderWriter::HeaderFile::WriteElements(std::ofstream& Target, HeaderWriter* Writer)
{
	std::set<std::string> Headers = {
		"kui/UI/UIBox.h",
		"kui/Markup/MarkupBox.h",
		"kui/Markup/Markup.h"
	};

	std::set<std::string> Dependencies;

	Target << "// Autogenerated code. Will be regenerated after each build, do not change.\n";
	Target << "// Generated by KlemmUIHT\n\n";
	Target << "#pragma once\n";

	for (auto& i : Elements)
	{
		i.Writer->GetDependencies(Dependencies);
	}

	for (auto& i : Dependencies)
	{
		if (UIElement::IsDefaultElement(i))
		{
			Headers.insert("kui/UI/" + i + ".h");
		}
		else
		{
			auto e = Writer->Parsed->GetElement(i);
			if (e && e->File + ".hpp" != this->Name)
			{
				Headers.insert(e->File + ".hpp");
			}
		}
	}

	for (auto& i : Headers)
	{
		Target << "#include <" << i << ">\n";
	}

	for (auto& i : Elements)
	{
		i.Writer->Write(Target);
	}
}